import Head from 'next/head'
import Hero from '../components/Home/Hero'
import HomeList from '../components/Home/homeList'
import Layout from '../components/Layout/Layout'

const Home = () => {

  return (
    <>
      <Head>
        <title>Dueño Directo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Hero />
        <HomeList />
      </Layout>
    </>
  )
}
export default Home
