import Head from 'next/head'
import Hero from '../components/Home/Hero'
import HomeList from '../components/Home/homeList'
import Layout from '../components/Layout/Layout'
import { sanityClient } from '../sanity'

const Home = ({ properties }) => {

  console.log(properties[0].slug.current)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Hero />
        <HomeList properties={properties} />
      </Layout>
    </>
  )
}

export const getServerSideProps = async () => {
  const query = `*[_type == "property"]`
  const properties = await sanityClient.fetch(query)

  if (!properties.length) {
    return {
      props: {
        properties: []
      }
    }
  } else {
    return {
      props: {
        properties
      }
    }
  }
}

export default Home
